### ISSUE TITLE
freshness in terminology

### ISSUE THREAD

**Issue by chrysn** [core-wg/echo-request-tag#62]
From Ines' Genart review:

> 1.- It would be nice to have the definition of Freshness into the terminology
> section.

@gselander and @emanjon, do you know of established references we could use there to avoid rolling our own definition?

**Comment by emanjon** [comment]
Hi,

Googling a bit, I think we might need to define this ourselves. Found some papers and
presentations taking about freshness, but they did not define it well. Found a very
mathematical definition in some other paper that we do not want to use.

I suggest something like this:

Freshness is a measure of the time since time since the message was sent. What is
considered a fresh message is application dependent. The Echo mechanism
specified in this document allow a server to calculate an upper bound for when
the message was encrypted. With this bound, the server can either verify that the
message is fresh (fresher than some application defined limit) or determine that
it cannot be verified that the message is fresh.

Cheers,
John

**Comment by chrysn** [comment]
Maybe we can slim that down and avoid talking of time too much (because yes it's time even in the event-based case, but a very odd discrete time, so might confuse people):

> Freshness is a measure of when a message was sent. A server that receives a request can either verify that the request is fresh or determine that it cannot be verified that the request is fresh. What is considered a fresh message is application dependent; example definitions are "no more than one hour ago" or "after this server's last reboot".

Would that work for you?
